apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mack91/portfolio-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"       
            memory: "128Mi"
          limits:
            cpu: "250m"      # Límite de 1/4 de núcleo
            memory: "256Mi"
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10   # Espera 10s antes de preguntar la primera vez
          periodSeconds: 15         # Vuelve a preguntar cada 15 segundos
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5    # Empieza a comprobar si está listo a los 5s
          periodSeconds: 10         # Comprueba cada 10 segundos
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
