apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mack91/portfolio-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"       # Lo mínimo que el clúster le reserva
            memory: "64Mi"
          limits:
            cpu: "100m"      # El "techo" máximo (10% de un núcleo)
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
